### PR TITLE
Deeper dissection of Quorum packets and Reconfig packets

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Hello,

The patch set enables deeper dissection of quorum packets(ProposalQP, CommitQP, and so on).
The patch set also includes dissector for Reconfig request/response and several optional features for debugging.

I made these patches for [earthquake](https://github.com/osrg/earthquake/), our model checker for real implementation of distributed systems(Zookeeper and so on).

Earthquakes permutes function calls, packets, and injected fault events in various orders to find bugs of the distributed system.

Zktraffic is used to make digests of packets so as to reduce the state exploration space.
https://github.com/osrg/earthquake/tree/master/example/zk.ether

### CODE REVIEW

**Comment by rgs1** [comment]
Thanks for the pull request @AkihiroSuda ! It looks good, I added a few comments, let me know if you have any questions!

**Comment by AkihiroSuda** [comment]
@rgs1 Than your for response!
I will fix it later.

**Comment by rgs1** [comment]
@AkihiroSuda : let me know if you want more time to get to the review, otherwise I am happy to merge it as is and follow-up with the style fixes in future commits. Thanks!

**Comment by AkihiroSuda** [comment]
@rgs1 
Thank you for the offer for merging!
I'd appreciate if you could merge the latest commits (3d57165 is an important, but the others are just style fixes).

**Comment by rgs1** [comment]
Merged, thanks @AkihiroSuda !

**Pull request merged**
